## Inisiasi Embedding

In [82]:
import numpy as np

# List of words limited to 22
words = ['nikmati', 'senang', 'bareng', 'teman', 'tetap', 'produktif', 'buat', 'bekerja', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>']

# Dictionary of embeddings
embeddings = {
    'nikmati': [-1.36, -1.66, 2.38, 6.54, -0.40, -1.5, 5.1, -1.75],
    'senang': [-0.94, -2.41, 0.65, 7.52, 0.85, -1.10, 4.12, -3.24],
    'bareng': [-0.46, -0.60, 0.33, 1.45, 0.29, -0.34, 1.48, 0.00],
    'teman': [-1.36, -1.67, 2.39, 6.55, -0.40, -1.51, 5.15, -1.75],
    'tetap': [0.24, -0.20, -0.10, 0.64, 0.51, -0.01, 0.33, 0.05],
    'produktif': [-0.09, -0.74, 0.19, 2.53, 0.94, -0.51, 1.87, 0.14],
    'buat': [0.74, -0.32, 0.11, 1.58, 0.96, 0.08, 0.98, 0.31],
    'bekerja': [3.24, 1.33, -1.96, 6.81, 6.63, 2.82, 4.45, 5.04],
    '<pad>': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
}

# Generate embeddings for the word list
final_embeddings = np.array([embeddings[word] for word in words])

print("Final Embeddings:\n", final_embeddings)


Final Embeddings:
 [[-1.36 -1.66  2.38  6.54 -0.4  -1.5   5.1  -1.75]
 [-0.94 -2.41  0.65  7.52  0.85 -1.1   4.12 -3.24]
 [-0.46 -0.6   0.33  1.45  0.29 -0.34  1.48  0.  ]
 [-1.36 -1.67  2.39  6.55 -0.4  -1.51  5.15 -1.75]
 [ 0.24 -0.2  -0.1   0.64  0.51 -0.01  0.33  0.05]
 [-0.09 -0.74  0.19  2.53  0.94 -0.51  1.87  0.14]
 [ 0.74 -0.32  0.11  1.58  0.96  0.08  0.98  0.31]
 [ 3.24  1.33 -1.96  6.81  6.63  2.82  4.45  5.04]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0. 

## Convolutional Layer

In [83]:
# Define a filter
num_filters = 128
kernel_size = 5
input_channels = final_embeddings.shape[1]
filters = np.random.rand(num_filters, kernel_size, input_channels)

# Convolution operation
def convolution(embeddings, filters):
    conv_output = np.zeros((embeddings.shape[0], num_filters))
    for f in range(num_filters):
        for i in range(embeddings.shape[0] - kernel_size + 1):
            segment = embeddings[i:i+kernel_size]
            conv_result = np.sum(segment * filters[f])
            conv_output[i, f] = conv_result
    return conv_output

conv_output = convolution(final_embeddings, filters)

print("Convolution Output Shape:", conv_output.shape)
print("Convolution Output:\n", conv_output)


Convolution Output Shape: (22, 128)
Convolution Output:
 [[10.67848718  9.20679402  0.58681391 ... 11.46108695 17.86804459
  15.83426501]
 [ 7.79326065  8.60276319  4.45801443 ... 10.49438166 19.61652472
  15.06051745]
 [11.16965034  9.89511638  4.04394125 ...  9.66217265 10.47722164
  10.00835689]
 ...
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]]


In [84]:
filters

array([[[0.85534672, 0.64842836, 0.03096075, ..., 0.44195843,
         0.29006436, 0.48695636],
        [0.01289663, 0.67800411, 0.30878311, ..., 0.60747222,
         0.72780657, 0.25601188],
        [0.62181388, 0.57330259, 0.05996161, ..., 0.38908518,
         0.82654894, 0.44574168],
        [0.61505763, 0.79286451, 0.55688229, ..., 0.67190694,
         0.83347168, 0.27683466],
        [0.00911506, 0.23117706, 0.18512836, ..., 0.85763986,
         0.32926598, 0.93292564]],

       [[0.14111073, 0.25712964, 0.90087368, ..., 0.78485264,
         0.55083012, 0.18128982],
        [0.05704978, 0.64577111, 0.41197533, ..., 0.18244205,
         0.62688888, 0.50565689],
        [0.71894334, 0.18776929, 0.87552553, ..., 0.21735509,
         0.00803255, 0.11751525],
        [0.90348196, 0.35635498, 0.001667  , ..., 0.07509205,
         0.50392834, 0.43002397],
        [0.1718355 , 0.406734  , 0.79247899, ..., 0.7843818 ,
         0.88837053, 0.57840054]],

       [[0.51375656, 0.7950316 , 0.9

## Relu Activation

In [85]:
# ReLU activation
def relu(x):
    return np.maximum(0, x)

relu_output = relu(conv_output)

print("ReLU Output Shape:", relu_output.shape)
print("ReLU Output:\n", relu_output)


ReLU Output Shape: (22, 128)
ReLU Output:
 [[10.67848718  9.20679402  0.58681391 ... 11.46108695 17.86804459
  15.83426501]
 [ 7.79326065  8.60276319  4.45801443 ... 10.49438166 19.61652472
  15.06051745]
 [11.16965034  9.89511638  4.04394125 ...  9.66217265 10.47722164
  10.00835689]
 ...
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]]


## Max Pooling Layer

In [86]:
# Max pooling operation
def max_pooling(x, pool_size, stride):
    pool_output = []
    for i in range(0, len(x) - pool_size + 1, stride):
        pool_segment = x[i:i+pool_size]
        pool_result = np.max(pool_segment, axis=0)
        pool_output.append(pool_result)
    return np.array(pool_output)

pool_output = max_pooling(relu_output, 2, 2)

print("Pooling Output Shape:", pool_output.shape)
print("Pooling Output:\n", pool_output)

Pooling Output Shape: (11, 128)
Pooling Output:
 [[10.67848718  9.20679402  4.45801443 ... 11.46108695 19.61652472
  15.83426501]
 [20.36808029 25.46340654 17.62362897 ... 22.46157915 31.79565703
  31.47100482]
 [22.22906127 20.77170084 21.70847748 ... 21.83888484 21.9809792
  17.14633349]
 ...
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]]


## Fully Connected Layer

In [87]:
# Softmax function
def softmax(x):
    exp_x = np.exp(x - np.max(x))  # Subtracting np.max(x) for numerical stability
    return exp_x / exp_x.sum(axis=0)

# Assuming we directly classify using pooled features, we need to reduce dimensions to match class number
output_weights = np.random.rand(pool_output.shape[1], 6)  # Output weights for 6 classes
output_bias = np.random.rand(6)  # Output bias for 6 classes

# Output layer computation
output = np.dot(pool_output.mean(axis=0), output_weights) + output_bias

softmax_output = softmax(output)

emotion_labels = ['joy', 'sad', 'fear', 'anger', 'neutral', 'love']

# Print output with emotion labels
print("\nSoftmax Output with Emotion Labels:")
for label, prob in zip(emotion_labels, softmax_output):
    print(f"{label}: {prob:.4f}")


Softmax Output with Emotion Labels:
joy: 0.0000
sad: 0.0000
fear: 0.0000
anger: 0.0000
neutral: 0.0000
love: 1.0000
